.MODEL SMALL
.STACK 100H
.DATA
    BCD_NUM1 DB 12H
    BCD_NUM2 DB 34H  
    RESULT DB ?
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX    
    MOV AX, 0
    
    MOV AL, BCD_NUM1
    ADD AL, BCD_NUM2
    DAA
    MOV RESULT, AL
    MOV AH, 4CH
    INT 21H
MAIN ENDP
END MAIN