.MODEL SMALL
.STACK 100H
.DATA
    MESSAGE DB 'HELLO WORLD!$'
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    MOV AH, 09H
    LEA DX, MESSAGE
    INT 21H
    MOV AH, 4CH
    INT 21H
MAIN ENDP
END MAIN